server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar?serverTimeZone=ADT
    username: postgres
    password: 123456
  Jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
